# SPDX-FileCopyrightText: 2026 Caracu contributors
# SPDX-License-Identifier: GPL-3.0+
cmake_minimum_required(VERSION 3.25)
foreach(required EXECUTABLE DEPENDENCIES DESTINATION SOURCE)
	if(NOT DEFINED ${required} OR NOT IS_ABSOLUTE "${${required}}")
		message(FATAL_ERROR "${required} must be an absolute path")
	endif()
endforeach()
if(EXISTS "${DESTINATION}")
	message(FATAL_ERROR "Refusing to overwrite an existing package directory")
endif()
set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM windows+pe)
set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL dumpbin)
find_program(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND dumpbin REQUIRED)
file(TO_CMAKE_PATH "$ENV{SystemRoot}" windows_root)
string(TOLOWER "${windows_root}/" windows_root_lower)
set(windows_pattern "${windows_root_lower}")
foreach(letter a b c d e f g h i j k l m n o p q r s t u v w x y z)
	string(TOUPPER "${letter}" upper)
	string(REPLACE "${letter}" "[${letter}${upper}]" windows_pattern "${windows_pattern}")
endforeach()
string(REPLACE "/" "[/\\\\]" windows_pattern "${windows_pattern}")
file(GET_RUNTIME_DEPENDENCIES EXECUTABLES "${EXECUTABLE}"
	DIRECTORIES "${DEPENDENCIES}/bin"
	RESOLVED_DEPENDENCIES_VAR runtime_dlls
	UNRESOLVED_DEPENDENCIES_VAR unresolved_dlls
	PRE_EXCLUDE_REGEXES "api-ms-.*" "ext-ms-.*"
	POST_EXCLUDE_REGEXES "^${windows_pattern}.*")
if(unresolved_dlls)
	message(STATUS "Resolved before failure: ${runtime_dlls}")
	message(FATAL_ERROR "Unresolved runtime DLLs: ${unresolved_dlls}")
endif()
set(copy_dlls "")
foreach(dll IN LISTS runtime_dlls)
	get_filename_component(name "${dll}" NAME)
	string(TOLOWER "${name}" name_lower)
	if(name_lower MATCHES "^qt[0-9].*\\.dll$")
		message(FATAL_ERROR "Qt runtime dependency found: ${dll}")
	endif()
	file(TO_CMAKE_PATH "${dll}" normalized_dll)
	string(TOLOWER "${normalized_dll}" dll_lower)
	string(FIND "${dll_lower}" "${windows_root_lower}" system_position)
	if(NOT system_position EQUAL 0)
		list(APPEND copy_dlls "${dll}")
	endif()
endforeach()
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY "${EXECUTABLE}" ${copy_dlls} DESTINATION "${DESTINATION}")
get_filename_component(executable_dir "${EXECUTABLE}" DIRECTORY)
file(COPY "${executable_dir}/resources" DESTINATION "${DESTINATION}")
file(COPY "${SOURCE}/COPYING.GPLv3" "${SOURCE}/caracu-windows-dependencies.lock.json"
	"${SOURCE}/CARACU-WORKBENCH.md" DESTINATION "${DESTINATION}")
file(COPY "${DEPENDENCIES}/licenses" DESTINATION "${DESTINATION}/dependency-notices")
file(GLOB_RECURSE source_notices RELATIVE "${SOURCE}" "${SOURCE}/3rdparty/*LICENSE*" "${SOURCE}/3rdparty/*COPYING*")
foreach(notice IN LISTS source_notices)
	get_filename_component(notice_directory "${notice}" DIRECTORY)
	file(COPY "${SOURCE}/${notice}" DESTINATION "${DESTINATION}/source-notices/${notice_directory}")
endforeach()
file(SHA256 "${EXECUTABLE}" exe_sha)
execute_process(COMMAND git rev-parse HEAD WORKING_DIRECTORY "${SOURCE}" OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE)
file(WRITE "${DESTINATION}/BUILD-IDENTITY.txt"
	"Source repository: https://github.com/mariocjun/caracu-pcsx2\nRevision: ${revision}\nExecutable SHA-256: ${exe_sha}\nInspect hello.source_dirty_at_configure; a dirty build is not identical to its HEAD.\nGPL and dependency notices are included. Keep the corresponding source with any distribution.\nNo BIOS, ROMs, game data, or personal profiles included.\nWindows MSVC runtime and system graphics drivers are prerequisites.\n")
message(STATUS "Packaged no-Qt PE dependency closure: ${DESTINATION}")
